[project]
name = "example-project"
version = "1.0.0"
sbom-files = [
    # Files and conditional SBOM files supported with markers
    {sbom-file = "conditional.cdx.json", markers = "platform_system = 'Windows'"},
]