[project]
name = "example-project"
version = "1.0.0"
sbom-files = [
    # Files and conditional SBOM files supported with tags
    {sbom-file = "conditional.cdx.json", platform = "win*"},
    {sbom-file = "conditional.cdx.json", python = "py2"},
]